Update build script to publish code to my S3 repo

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -1,3 +1,13 @@
+CONFIG_BUCKET=$1
+CODE_BUCKET=$2
+
+if [ $# -ne 2 ]
+then
+    echo "Usage: deploy <config-bucket> <deploy-bucket>"
+    echo " (If you can't remember the exact name of your buckets, run 'aws s3 ls')"
+    exit 1
+fi
+
 echo "Deleting existing build folder..."
 rm -rf build/
 echo "Copying files to build dir"
@@ -13,7 +23,10 @@ do
 done
 cd build
 rm *.test.js
+echo "Fetching configuration from $CONFIG_BUCKET in S3..."
+aws s3 s3://$CONFIG_BUCKET .
 echo "Installing production deps in build"
 npm install --only=production
-zip -r build.zip *
+echo "Syncing code to $CODE_BUCKET bucket in S3..."
+aws s3 sync . s3://$CODE_BUCKET
 cd ..
